# Generated by Django 4.2.13 on 2024-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='website_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
