# Generated by Django 4.2.13 on 2024-06-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_urls_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
